### ISSUE TITLE
factory-guy appears to be incompatible with Fastboot

### ISSUE THREAD

**Issue by gabrielgrant** [danielspaniel/ember-data-factory-guy#282] opened 2017-04-06 11:50 UTC
Factory guy's usage of Mockjax seems to cause Fastboot to fail with:

```
Cannot read property 'ajax' of undefined
TypeError: Cannot read property 'ajax' of undefined
```

The error appears to come from [this line in mockjax](https://github.com/jakerella/jquery-mockjax/blob/13d517cfde612ef89352415a49efbc13e194a7a0/src/jquery.mockjax.js#L26). 

[Apparently "to use Mockjax as a Node module you MUST provide the factory with a valid version of jQuery and a window object"](https://github.com/jakerella/jquery-mockjax/blob/13d517cfde612ef89352415a49efbc13e194a7a0/src/jquery.mockjax.js#L13)

Not sure that it's a good idea to get into shimming jquery functionality in fastboot, though. So maybe best to just [avoid pulling mockjax into the fastboot build at all by adding a guard](https://github.com/ember-fastboot/ember-cli-fastboot/issues/133#issuecomment-207548884) to [the `app.import() call`](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/index.js#L37) (or adjusting the conditions on [the existing guard](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/index.js#L48))

**Comment by danielspaniel** [comment] 2017-04-06 11:54
Can you PR this one @gabrielgrant .. ?

**Comment by danielspaniel** [comment] 2017-04-06 20:01
can you check if this release fixes this issue?
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.12.3

**Comment by danielspaniel** [comment] 2017-05-31 02:41
I am closing this assuming it works now because of fixes in 2.12.3 .. but open it again if I am mistaken

**Comment by roschaefer** [comment] 2017-10-20 17:50
Hey @danielspaniel could you reopen? I'm converting an existing Ember app to ember-fastboot and I'm running into this.

[See our PR in order to discover fastboot incompatible plugins](https://github.com/roschaefer/rundfunk-mitbestimmen/pull/360), which surprisingly includes `ember-data-factory-guy`.

You can reproduce the issue by checkout out the branch and install `ember-data-factory-guy`:
1. `git clone -b ember-fastboot git@github.com:roschaefer/rundfunk-mitbestimmen.git`
2. `cd frontend`
3. `yarn install && ember install`
4. `ember install ember-data-factory-guy`
5. Visit `http://localhost:4200`
6. Enjoy `TypeError: Cannot read property 'ajax' of undefined` :boom: 

```
/home/robert/Development/Rails/rfm-fastboot/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-uhrJqKF1.tmp/assets/vendor.js:76060
	var _ajax = $.ajax,
	             ^

TypeError: Cannot read property 'ajax' of undefined
    at /home/robert/Development/Rails/rfm-fastboot/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-uhrJqKF1.tmp/assets/vendor/jquery-mockjax/jquery.mockjax.js:26:1
    at /home/robert/Development/Rails/rfm-fastboot/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-uhrJqKF1.tmp/assets/vendor/jquery-mockjax/jquery.mockjax.js:21:1
    at /home/robert/Development/Rails/rfm-fastboot/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-uhrJqKF1.tmp/assets/vendor/jquery-mockjax/jquery.mockjax.js:23:1
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VMSandbox.eval (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/ember-app.js:156:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/ember-app.js:153:21)
    at EmberApp.retrieveSandboxedApp (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/fastboot/src/index.js:52:10)
    at app.use (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/ember-cli-fastboot/index.js:298:29)
    at Layer.handle [as handle_request] (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/express/lib/router/index.js:317:13)
    at /home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/express/lib/router/index.js:335:12)
    at next (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/express/lib/router/index.js:275:10)
    at err (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatch (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
    at invokeCallback (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
    at /home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/home/robert/Development/Rails/rfm-fastboot/frontend/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

```shell
$ ember --version
ember-cli: 2.16.2
node: 8.3.0
os: linux x64
```

**Comment by danielspaniel** [comment] 2017-10-20 17:54
If you have an idea of how to fix this ( like replacing mockjax with pretender or something that does not use jquery namespace ) then I am up for it. Just might be a bit of work,  not sure how much though.

**Comment by roschaefer** [comment] 2017-10-20 18:01
I'm currently learning on ember-fastboot and don't feel confident yet to tackle this issue. The only question I have so far: Why does a testing plugin interfere with ember-fastboot at all in development/production environment?

**Comment by danielspaniel** [comment] 2017-10-20 18:04
maybe because in the fastboot environment there is no jquery and therefore, since mockjax depends on jquery .. it is pretty much blowing up when you try and install mockjax without jquery. 
 could you learn ember on plain ember ( without fastboot ) ?

**Comment by danielspaniel** [comment] 2017-10-20 18:05
I think I should probably fix this issue myself then .. since I can probably do it faster and easier.  Let me research a bit ( already started ) and see what I can do.  Don't hold breath though. might be big job.

**Comment by gabrielgrant** [comment] 2017-10-20 21:15
@danielspaniel sorry i never got back to this issue, we changed the way we were testing to not depend on factory-guy before i had tackled this. My understanding from the research I was doing earlier, though, was that this could be worked around by just excluding mockjax from the build in fastboot, without making any changes to factory-guy

Right now the very presence of factory-guy breaks the fastboot build, even if nothing to do with my production app uses factory-guy (as, i imagine, is generally the case). I think what @roschaefer was asking was whether there is any reason that factory-guy itself needs to actually be able to *run successfully* under fastboot? This is basically what I was suggesting -- in my case, at least, just having my app load within fastboot would have been sufficient, I didn't need to run any of the parts of my app that actually touched factory-guy in the fastboot context. Hope that makes sense?

**Comment by roschaefer** [comment] 2017-10-21 21:48
@gabrielgrant Yes! That was exactly what I meant. Not having mockjax in fastboot would work for us, too!

**Comment by danielspaniel** [comment] 2017-10-21 21:58
I see what you mean ( both of you ) but the trick is .. how to not load factory-guy when fastboot loading.  Not sure how to do that.  Any ideas?  Maybe it is so easy I am missing it.

**Comment by roschaefer** [comment] 2017-10-21 22:27
I found https://github.com/ember-fastboot/ember-cli-fastboot/issues/413
and https://github.com/kratiahuja/fastboot-transform

Is it relevant for our problem?

**Comment by danielspaniel** [comment] 2017-10-21 22:51
That is pretty relevant, but not so easy to find the light at the end of the tunnel.  I might have another solution in a few days anyway. So stay tuned.

**Comment by danielspaniel** [comment] 2017-10-25 09:25
I have an update to factory guy in a few days that will work in fastboot. it is a bit change to underlying code, so I am testing it out a bit on my own projects. But will be ready by the weekend.

**Comment by danielspaniel** [comment] 2017-10-28 15:04
@roschaefer  can you do me a favour and try out this branch of factory guy and let me know if it works for fastboot for you ? 

   steps: 

  first remove the factory guy line from package.json 
  then npm prune 
  then add this line to package.json  =>    "ember-data-factory-guy": "danielspaniel/ember-data-factory-guy#pretender"

  and then npm install

**Comment by roschaefer** [comment] 2017-10-28 17:21
Sure!

I get:
```
Error: Could not find module `pretender` imported from `ember-data-factory-guy/mocks/request-manager`
```

**Comment by danielspaniel** [comment] 2017-10-28 17:26
ok .. well that is a start .. is this a public repo I could check out ?

**Comment by roschaefer** [comment] 2017-10-28 17:29
Here: https://github.com/roschaefer/rundfunk-mitbestimmen/pull/360

You can do `git clone git@github.com:roschaefer/rundfunk-mitbestimmen.git && git checkout ember-fastboot`

I'll push the commits, probably it's just because I don't have the `pretender` module in `development` environment (as in the README of the branch)

**Comment by roschaefer** [comment] 2017-10-28 22:10
Refactored our frontend tests and they all pass now :tada: 

Thank you for the generic `mock` for arbitrary requests :wink:

**Comment by danielspaniel** [comment] 2017-10-28 22:15
Whooray .. that is awesome .. I will merge that to master then 💃   

 I used the $.mockjax freestyle pretty often so I knew it would be important to keep that one in. I am surprised you found that one, since I did not put any documentation in for that .. good job finding that one.

**Comment by danielspaniel** [comment] 2017-10-28 22:17
The fastboot part still not working ?  or is it?

**Comment by roschaefer** [comment] 2017-10-28 22:21
Nope, I still get the
```
Error: Could not find module `pretender` imported from `ember-data-factory-guy/mocks/request-manager`
```
 error. I'm not familiar with the build pipeline of Ember and wanted to investigate a little..

**Comment by danielspaniel** [comment] 2017-10-28 22:22
ok .. should I clone your repo, switch to that fastboot branch and run ember build .. to see the error ?

**Comment by roschaefer** [comment] 2017-10-28 22:23
that would be possible

**Comment by danielspaniel** [comment] 2017-10-29 15:22
v2.13.9 ( just released )  now works when fastboot is running. ( although of course you can't use mocking since pretender does not support the fetch command yet ) 
 thanks so much for expending the calories by typing out this issue .. you have lost weight and contributed to the project!

**Closed by danielspaniel** 2017-10-29 15:22 UTC

**Comment by roschaefer** [comment] 2017-10-30 17:51
That's pretty awesome!

I don't want to ruin the good vibes but I checked out the branch again, installed `2.13.10` and now I get the following error when I do `ember serve`:
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open '/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/source_map_concat-input_base_path-gY
4BjgmE.tmp/vendor/pretender-shim.js'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at SourceMap.addFile (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (<anonymous>:null:null)
    at Concat.<anonymous> (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/broccoli-concat/concat.js:198:24)
    at /home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:1039:33)
    at SourceMap.end (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/fast-sourcemap-concat/lib/source-map.js:406:10)
    at Concat._doLegacyBuild (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/broccoli-concat/concat.js:183:22)
    at Concat.build (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/broccoli-concat/concat.js:106:17)
    at /home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
```

It seems to break our build server, too: https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/294723450?utm_source=github_status&utm_medium=notification

Am I missing or do I have to configure sth.?

**Comment by danielspaniel** [comment] 2017-10-30 18:12
what a pooper .. ok .. good to know .. i get on it

**Comment by danielspaniel** [comment] 2017-10-30 22:12
can you give v2.13.11 a try .. i removed that import

**Comment by roschaefer** [comment] 2017-10-31 10:49
OK, e0031e28b85908dba6845e883ba0cffca776cdf9 fixed that error :+1:

On branch `ember-fastboot` I can run ember in `test` environment, but when I run in `development` I see the previous error in the browser:
```
Error: Could not find module `pretender` imported from `ember-data-factory-guy/mocks/request-manager`
    at missingModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:247:1)
    at findModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:258:1)
    at Module.findDeps (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:168:1)
    at findModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:168:1)
    at findModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:168:1)
    at findModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:168:1)
    at findModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:262:1)
    at requireModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:24:1)
    at resolveInitializer (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/addon-tree-output/ember-load-initializers/index.js:29:1)
    at registerInitializers (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/addon-tree-output/ember-load-initializers/index.js:42:1)
    at exports.default (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/addon-tree-output/ember-load-initializers/index.js:24:1)
    at Module.callback (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/frontend/app.js:15:1)
    at Module.exports (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:104:1)
    at Object.requireModule (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/tmp/broccoli_persistent_filterreplace_filter-output_path-pKypvETt.tmp/assets/vendor/loader/loader.js:27:1)
    at Object.<anonymous> (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/ember-app.js:179:18)
```

I just updated our master branch and when the build server succeeds we can merge `2.13.11`. Seems the error above is related to fastboot: https://github.com/roschaefer/rundfunk-mitbestimmen/pull/383

Any idea if the above error is related to this plugin or if it's a configuration issue?

**Comment by danielspaniel** [comment] 2017-10-31 10:53
You're right Robert. I was sleeping on that one, and realize that this one is hard, because that shim is only needed in fastboot environment ( ugh ) .. i know what I have to do now, I just afraid to step in the mud. Putting on my boots anyway.

**Comment by roschaefer** [comment] 2017-10-31 11:03
I start to feel guilty :worried:

Just to let you know: Migrating to fastboot is not an urgent issue for us. Our app also depends on one more plugin that needs to be fastbooterized. So we will probably not be able to migrate our application to fastboot anytime soon.

At the end of the week I have some time and I could help you out. That way, I could also learn sth. about the ember-fastboot world. Probably I will help to make the other plugin fastboot compliant: https://github.com/auth0-community/ember-simple-auth-auth0/issues/50#issuecomment-339156151

**Comment by danielspaniel** [comment] 2017-10-31 12:05
Don't feel guilty ( in this case ) because yes, you wanted fastboot support , but i think i had to do it anyway, because it was long overdue for factory-guy. If I still need help on weekend I will let you know.Thanks for the offering of your time.  😄

**Comment by roschaefer** [comment] 2017-11-06 15:29
Hooray. I got noticed by our dependency bot @dependabot that there is a new version of `ember-data-factory-guy`. I tested the new version locally and I can confirm that ember-fastboot now works as expected.

**Comment by danielspaniel** [comment] 2017-11-06 18:23
Yes, I finally found the issue that was causing my hair to fall out. Thanks for confirming it all works fine now.

**Comment by gabrielgrant** [comment] 2017-11-11 02:48
@danielspaniel @roschaefer thanks for working through the details to get this fixed, folks!
