### ISSUE TITLE
Support for multiple stores

### ISSUE THREAD

**Issue by thec0keman** [danielspaniel/ember-data-factory-guy#286] opened 2017-05-04 18:47 UTC
We are currently migrating a rather large ember app to ember-engines.  One thing that became clear early on was it would be advantageous to have separate stores for each engine.  However, this has a significant drawback for using factory guy in acceptance tests.  (Unit / integration still work just fine since we set up a custom resolver for in-engine tests).

Is there a way for factory guy to support engines with separate stores inside acceptance testing?  I'm not sure how exactly this could work, but it seems like the key issue is that factory guy assumes that any ED models are available in the main container.  Would it be possible to flag certain factories as only available within a specific engine domain?

**Comment by danielspaniel** [comment] 2017-05-05 04:40
There is a method  FactoryGuy.setStore(aStore)  which does what you would expect. 
 You can put your factories in test-support directory within the engine and it will be available to whole application, but if you put it in tests I think it will be limited to engine domain ( I could be wrong ) 
 But for me to asses what is possible and what is required I would have to see your setup. 
 I would be happy to screen share sometime with you or if you can put up a public repo and show me around I can work on / figure out the details in there.

**Comment by danielspaniel** [comment] 2017-05-05 16:47
Actually, now that I think about it I kind of don't get it:

Is there a way for factory guy to support engines with separate stores inside acceptance testing? 

 Not sure exactly what you mean .. so get in touch if you want to chat about it. I am curious to understand the issue fully.

**Comment by thec0keman** [comment] 2017-05-06 14:54
Hey, I can push up some code if it helps, but the structure is pretty simple:
- main app has ember-data
- in-repo engine has ember-data, but does not share a store with main app
- both apps share some models (from an in-repo addon)
- both apps also have unique models

We have factories set up for all models in `tests/factories`.

Both shared and unique factories work just fine with `build` and `make` in unit and integration tests because we use a custom resolver for these tests.  (as described [here](https://github.com/ember-engines/ember-engines#unitintegration-testing-for-in-repo-engines))

In acceptance tests:
- if you try to build a factory for an app-unique model, it works
- if you try to build a factory for a shared model, it works
- if you try try build a factory for an engine-unique model

This can look something like:
```
Error: No model was found for 'affiliate-change'
```

With a stack trace:
```
testem.js:989 Error
    at Class._modelFactoryFor (store.js:1813)
    at Class._modelFor (store.js:1797)
    at Class.modelFor (store.js:1790)
    at ModelDefinition.isModelAFragment (model-definition.js:52)
    at ModelDefinition.build (model-definition.js:195)
    at FactoryGuy.buildRaw (factory-guy.js:301)
    at FactoryGuy.build (factory-guy.js:286)
    at index-test.js:21
    at Class.andThen (ember.debug.js:38931)
    at ember.debug.js:38874
```

I was considering using`setStore` in these scenarios, since presumably the only problem is that with acceptance tests factory-guy is automatically plugging in to the main container/store and obviously cannot find the model there.  My thought was to call `setStore` in any tests that need a factory for an in-engine model with that engine's store.  However, I have not been able to figure out the right way to get the engine's store from a test context. :) 

What would be nice is a way to easily flag that specific factories should be looked up on a specific engine (perhaps similar to how you can set up custom resolvers for unit / integration tests).

**Comment by danielspaniel** [comment] 2017-05-07 20:41
Actually .. yes, if you can make a skeleton repo, with minimum amount of things ( especially with a nice2
 failing test ) I can noodle around and see what I can come up with. 
 
  I guess what you are saying is that if certain factories were not looked up then the factory would not blow up trying to find the model it can not find.  
 I am also guessing that the solution is either to limit the factories loaded ( like you are suggesting ) or including/loading all the model definitions in an acceptance test so they are all available. 

 I am just still confused as to how the whole thing fits together though, since I am not sure how you are declaring app vs shared vs engine models.  So a specific repo to play with would help.

**Comment by thec0keman** [comment] 2017-05-08 15:42
sounds good.  I'll try to get something up this week.

**Comment by thec0keman** [comment] 2017-05-08 22:29
Here is an [example repo](https://github.com/thec0keman/ember-engine-browserify-test/tree/factory-guy-example).  I left some comments in the test files trying to explain the expected outcome.

Thanks!

**Comment by danielspaniel** [comment] 2017-05-12 17:24
Okay .. here is my conclusion .. 
 There is a good reason that ember-engines talks how you can test you engine specific things in integration and unit tests.  
They don't say .. hey .. you can test engine specific stuff in the applicaiton. 

 So, when you run acceptance test ( in application land ) and you call for /commentator , which goes to commentator engine, that engine knows about it's models. 

 In an application acceptance test if you want to test the engine you have to go through the routing of the engine. You can not and should not be getting / making instances of  engine models in the application acceptance tests.  (( My opinion. )) There is something very fishy if you are doing that. 
 Since by design the UNIT testing ( models ) should be done in the engine. Right? 

 If you dissagree, let me know .. because otherwise this is an issue I or no one should fix. (( My opinion ... until you can convince me otherwise and then I will gladly disagree with myself ))

**Comment by thec0keman** [comment] 2017-05-12 19:20
Hey, thanks for working through this!

I agree you should not be making models as in using `make`, that clearly seems to be poor practice.  However, a common use case for Factory Guy in acceptance tests is building payload for a stubbed server (such as using [Pretender](https://github.com/pretenderjs/pretender) or Factory Guy's own `mock` helpers.  In these cases it would not be possible to mock an API endpoint in an acceptance test because Factory Guy depends on the model file itself.

(That was the reason I was wondering if it it would be possible just to flag a special resolver on the factory itself, since it really just needs to be able to load the JS file to build a payload, right?)

**Comment by danielspaniel** [comment] 2017-05-12 19:34
Now that is a very good point. 
 If you want to build a payload in the application level that includes engine models .. 
 
 BUT I think they assume that the engine routes/templates ( and therefore models) will be tested in acceptance tests FOR THAT engine. ?? ( i am guessing ) 

There probably is a way to resolve those models in the engine while running application tests ( so factory guy can resolve them too .. but you will probably need serializers and adapters too ) though I not sure how to do that at the moment. 

 Do you?

**Comment by thec0keman** [comment] 2017-05-12 21:33
Not really :) 

It is possible that is assumed, though that sort of defeats the point of an in-repo engine.  (Although maybe the thought is in-repo engines are a temporary step?)

But yeah, seems like the serializers / adapters are the tough point since that would require actually getting the engine's store.  I've done some poking (and posted on the Ember slack), but haven't made much progress.

**Comment by danielspaniel** [comment] 2017-05-12 21:36
I know .. it is a bummer. 
 And good to know you asked on the slack channels because I was thinking of same. 
 I think for sure there is a way to do it, but I just don't know how right now. 

  I guess if I were you I would make acceptance tests for the in-repo engines routes. 
 Is that doable?  
  Does that cover most of what needs covering?

**Comment by danielspaniel** [comment] 2017-05-15 17:44
I have not given up yet :)  I was hoping to get something working where 2 resolvers would be allowed at the same time.  ember-mocha docs alluded to such a thing, but it did not quite work. 
 This would be the easiest solution ( though easy is still hard ) if I can figure out how to do it

**Comment by danielspaniel** [comment] 2017-05-17 21:36
Ok .. I have  now officially given up. 
You can't have multiple resolvers in a test, so that settles that. 
 I will still try and think of a way to do this in the future, but for now I think this is just a limitation of factory guy.

**Comment by thec0keman** [comment] 2017-05-20 04:10
Thanks for being so diligent in trying to solve this!  A new technology like ember-engines often comes with short term limitations like this so while it is a bummer, it is perfectly understandable.  I hope as engines matures there will be increased API tooling that could also help with this.

Just out of curiosity, when you said `make acceptance tests for the in-repo engine routes`, did you mean add tests within the in-repo addon itself?  AFAIK acceptance tests are always scoped to the main app, and I haven't come across an example where an in-repo addon would have its own test suite.  If we extracted the in-repo engine to a separate repo, in theory it could have its own test suite, but I'm pretty sure that test suite would inherit the same issues: it would have a dummy parent app that mounts the engine.

In any case, the short term solution of just mocking ad hoc JSON for these acceptance tests works.  Honestly the elegance of factory-guy has kind of spoiled us. :)

**Comment by danielspaniel** [comment] 2017-05-31 02:40
Sure .. let's close it for now. Thanks for asking. I will just close it now, and if we ever think of how to resolve it we can open again.

**Closed by danielspaniel** 2017-05-31 02:40 UTC
