### ISSUE TITLE
Building data attributes for JSONAPIAdapter not working as expected

### ISSUE THREAD

**Issue by davetheninja** [danielspaniel/ember-data-factory-guy#108] opened 2015-07-20 14:51 UTC
Firstly, apologies for being AWOL for the require.js pull request. Family and work have kept me offline for the last while.

The issue:

When factory_guy is building the mockjax response for the JSONAPIAdapter it is building the attributes section in the same camelCasing as the models field names.

So, instead of say:

```javascript
attributes: {
  'first-name': 'David'
}
```

It is generating:

```javascript
attributes: {
  firstName: 'David'
}
```

When this happens, Ember's JSONAPISerializer ignores the attribute as it is expecting the hyphenated version.

I am wondering if a) I am missing something obvious or b) its a bug.

If its a bug I would be more than happy to help fix it, however I would like to discuss the best way (in your opinion) to go about it.

Thanks again.

**Comment by danielspaniel** [comment] 2015-07-20 14:58
@davetheninja .. no worries .. gosh that was a while ago.. right, well .. in this case .. it would be supercalafragalistic if you could put together something like a failing test that shows me what you mean. I can image a few things, but the failing test would make it obvious in a more warm and fuzzy kind of way.

**Comment by davetheninja** [comment] 2015-07-20 15:05
Consider it done.

**Comment by davetheninja** [comment] 2015-07-20 15:48
Smashed together a really simple example.

https://github.com/davetheninja/factory-guy-issue

You will see that the fullName attribute is being ignored as its not hyphenated.

**Comment by davetheninja** [comment] 2015-07-20 15:53
Tracked it down to factory-guy.js convertSingle / extractAttributes.

its doing a 1:1 on the field name:attribute name.  If JSONAPI this should lowercase hyphenate the attribute name.

**Comment by danielspaniel** [comment] 2015-07-20 15:55
boy that was quick! .. this is quality example .. you want to do PR or want me to fix it?

**Comment by davetheninja** [comment] 2015-07-20 15:57
Its just pushing midnight here so if you have time please go ahead, if not ill pick it up again tomorrow.  In HK so timezone wins tonight.

**Comment by danielspaniel** [comment] 2015-07-20 15:59
got it .. will do .. thanks and happy z

**Comment by danielspaniel** [comment] 2015-07-21 01:38
hmm .. pretty interesting . so far, in trying to recreate that .. I have found that JSONApi adapter fine with camelcase atrributes on a findAll ( so I could not duplicate that test yet ) .. but not ActiveModelAdapter ( the only test failing ) .. kind of strange ..

**Comment by danielspaniel** [comment] 2015-07-21 01:45
also .. just so you know .. the jsonapi format I don't think means to say .. you have to have dasherized attributes .. you can have camelCase ones .. and you could even  manipulate things in the serializers/adapters where you can say if the keys should be this or that even though I am passing you this or that .. etc .. but it seems by default do handle camel casing .. as far as I can tell 
 
I wrote a test like this (that passes for jsonapi):

```javascript
  test("handles camelCase attributes", function (assert) {
    Ember.run(function () {
      var done = assert.async();

      TestHelper.handleFindAll('profile', 1);

      FactoryGuy.getStore().findAll('profile').then(function (profiles) {
        ok(profiles.get('firstObject.camelCaseDescription') === 'textGoesHere');
        done();
      });
    });
  });
```

model:

```javascript
export default DS.Model.extend({
  created_at:             DS.attr('date'),
  description:            DS.attr('string'),
  camelCaseDescription:   DS.attr('string'),
  snake_case_description: DS.attr('string'),
  company:                DS.belongsTo('company', {async: false}),
  group:                  DS.belongsTo('group', {async: false, polymorphic: true})
});
```

and factory:

```javascript
FactoryGuy.define('profile', {
  default: {
    description: 'Text goes here',
    camelCaseDescription: 'textGoesHere',
    snake_case_description: 'text_goes_here'
  }
});

```

**Comment by linstula** [comment] 2015-07-24 13:07
I've run into this same issue (it also happens with keys in the `relationships` object, as well as `attributes`) . It doesn't seem that dasherized keys are a strict requirement, but they are recommend: http://jsonapi.org/recommendations/#naming.

**Comment by danielspaniel** [comment] 2015-07-24 14:47
boy .. I sure wish I could get a failing test for this one.
I just can't seem to recreate this issue in the test suite.
Do you think you could do a PR with a failing test ( one that shows this issue )? 
 What did you do to get around the issue?

**Comment by davetheninja** [comment] 2015-07-24 14:50
Can you send me a note on where you were trying to get a failing test in
the suite?

I should be back doing some money business tomorrow or Sunday. Was going to
take a stab at it.

Any pointers would do as I found the suite a bit difficult to get my head
around.

Although.... did you update to latest ember/ember-data? If not it could be
a bug in the latest release?

On 24 July 2015 at 22:47, Daniel Sudol <notifications@github.com> wrote:

> boy .. I sure wish I could get a failing test for this one.
> I just can't seem to recreate this issue in the test suite.
> Do you think you could do a PR with a failing test ( one that shows this
> issue )?
> What did you do to get around the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124546900>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by danielspaniel** [comment] 2015-07-24 14:51
ooo .. yeah .. that is very good point .. I have not updated to latest 1.3.5 .. so maybe if I do that . I can get a failure .. let me do that and get back to you

**Comment by davetheninja** [comment] 2015-07-24 14:52
IIRC Anything to do with attributes goes down the same code path eventually
(convertSingle -> extractAttributes)

Daniel correct me if i'm wrong.

On 24 July 2015 at 21:07, linstula <notifications@github.com> wrote:

> I've run into this same issue (it also happens with keys in the
> relationships object, as well as attributes) . It doesn't seem that
> dasherized keys are a strict requirement, but they are recommend:
> http://jsonapi.org/recommendations/#naming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124514350>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by davetheninja** [comment] 2015-07-24 14:52
Woot! My brain is still functioning!

On 24 July 2015 at 22:51, Daniel Sudol <notifications@github.com> wrote:

> ooo .. yeah .. that is very good point .. I have not updated to latest
> 1.3.5 .. so maybe if I do that . I can get a failure .. let me do that and
> get back to you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124548266>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by linstula** [comment] 2015-07-24 14:53
Can confirm that I was using ember-data 1.13.5 when I bumped into this

**Comment by danielspaniel** [comment] 2015-07-24 14:55
@davetheninja .. yes .. think you got that right 
 and great @linstula .. that settles that issue .. now I can fix it ... I will get back to you when I push it.

**Comment by davetheninja** [comment] 2015-07-24 14:56
Fantastic

On 24 July 2015 at 22:56, Daniel Sudol <notifications@github.com> wrote:

> @davetheninja <https://github.com/davetheninja> .. yes .. think you got
> that right
> and great @linstula <https://github.com/linstula> .. that settles that
> issue .. now I can fix it ... I will get back to you when I push it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124550194>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by linstula** [comment] 2015-07-24 14:56
awesome! :+1:

**Comment by danielspaniel** [comment] 2015-07-24 15:35
bad news .. I updated to ember-data 1.13.5, and the JSONAPI tests all acted like it they got free tickets to  a yankees game ( they were all happy ) ... except for handleUpdate tests ( which is not what you had trouble with right? ) your issue was handleFindAll .. ??

**Comment by davetheninja** [comment] 2015-07-24 15:49
In my case it was handleFindAll. 


This really is bizarre. 




Going out on a limb here, could the tests be giving false positives? 




I will have a look again at the weekend. Thanks again 





—

**Comment by davetheninja** [comment] 2015-07-24 15:54
Can you send me the test you were trying to fail (my heads in it so trying
now)



On 24 July 2015 at 23:49, David Lawton <david@davetheninja.net> wrote:

> In my case it was handleFindAll.
>
> This really is bizarre.
>
> Going out on a limb here, could the tests be giving false positives?
>
> I will have a look again at the weekend. Thanks again
>
> —
> Sent from Mailbox <https://www.dropbox.com/mailbox>
>
>
> On Fri, Jul 24, 2015 at 11:35 PM, Daniel Sudol <notifications@github.com>
> wrote:
>
>> bad news .. I updated to ember-data 1.13.5, and the JSONAPI tests all
>> acted like it they got free tickets to a yankees game ( they were all happy
>> ) ... except for handleUpdate tests ( which is not what you had trouble
>> with right? ) your issue was handleFindAll .. ??
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124560621>
>> .
>>
>
>


-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by linstula** [comment] 2015-07-24 16:19
I actually wasn't using the testHelpers - I was building a JSON response with `FactoryGuy.build` (using the JSONAPIAdapter) and sending that payload back with [Pretender](https://github.com/trek/pretender). the relationships and attributes that were camelCased had values of undefined on the resulting model instances. 

I did some digging and this seems to be a known case for the JSONAPISerializer (the issue is about the serializer not handling underscored keys but bmac mentions that, by default, the serializer expects dasherized keys): https://github.com/emberjs/data/issues/3455

Unsure why the tests are passing though :/. I haven't looked too deeply into the code but I suspect the tests may be pushing records directly into the store and side stepping part of the normal flow for turning a json payload into a model instance.

**Comment by davetheninja** [comment] 2015-07-24 16:29
I think I know why the tests (i just wrote on the helper) are not failing.
Its retrieving directly from factory guy profile.

I am going to write a quick acceptance test to confirm.

On 25 July 2015 at 00:19, linstula <notifications@github.com> wrote:

> I actually wasn't using the testHelpers - I was building a JSON response
> with FactoryGuy.build (using the JSONAPIAdapter) and sending that payload
> back with Pretender <https://github.com/trek/pretender>. the
> relationships and attributes that were camelCased had values of undefined
> on the resulting model instances.
>
> I did some digging and this seems to be a known case for the
> JSONAPISerializer (the issue is about the serializer not handling
> underscored keys but bmac mentions that, by default, the serializer expects
> dasherized keys): emberjs/data#3455
> <https://github.com/emberjs/data/issues/3455>
>
> Unsure why the tests are passing though :/. I haven't looked too deeply
> into the code but I suspect the tests may be pushing records directly into
> the store and side stepping part of the normal flow for turning a json
> payload into a model instance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124571364>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by davetheninja** [comment] 2015-07-24 17:08
Smoking gun found, shots came from the grassy knoll!!

Switch the adapter and serializer to JSONAPIAdapter and JSONAPISerializer

Bingo

On 25 July 2015 at 00:29, David Lawton <david@davetheninja.net> wrote:

> I think I know why the tests (i just wrote on the helper) are not
> failing.  Its retrieving directly from factory guy profile.
>
> I am going to write a quick acceptance test to confirm.
>
> On 25 July 2015 at 00:19, linstula <notifications@github.com> wrote:
>
>> I actually wasn't using the testHelpers - I was building a JSON response
>> with FactoryGuy.build (using the JSONAPIAdapter) and sending that
>> payload back with Pretender <https://github.com/trek/pretender>. the
>> relationships and attributes that were camelCased had values of undefined
>> on the resulting model instances.
>>
>> I did some digging and this seems to be a known case for the
>> JSONAPISerializer (the issue is about the serializer not handling
>> underscored keys but bmac mentions that, by default, the serializer expects
>> dasherized keys): emberjs/data#3455
>> <https://github.com/emberjs/data/issues/3455>
>>
>> Unsure why the tests are passing though :/. I haven't looked too deeply
>> into the code but I suspect the tests may be pushing records directly into
>> the store and side stepping part of the normal flow for turning a json
>> payload into a model instance.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124571364>
>> .
>>
>
>
>
> --
> "I am not able to rightly apprehend the kind of confusion of ideas that
> could provoke such a question." -- Charles Babbage
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by danielspaniel** [comment] 2015-07-24 17:08
The test is this one: 

```javascript
  test("handles camelCase attributes", function (assert) {
    Ember.run(function () {
      var done = assert.async();

      TestHelper.handleFindAll('profile', 1);

      FactoryGuy.getStore().findAll('profile').then(function (profiles) {
        ok(profiles.get('firstObject.camelCaseDescription') === 'textGoesHere');
        done();
      });
    });
  });
```

**Comment by danielspaniel** [comment] 2015-07-24 17:09
really .. you found real evidence .. jfk, I mean .. the test fails?

**Comment by davetheninja** [comment] 2015-07-24 17:13
I seriously doubt that one will fail as its testing internals to factory
guy.

The bug is between factory guy and mockjax -> jsoanapi not understanding
the attributes.

In my tired state i could not get git patch to work....

https://github.com/davetheninja/ember-data-factory-guy

checked in to a fork.

Please have a look-see

On 25 July 2015 at 01:09, Daniel Sudol <notifications@github.com> wrote:

> really .. you found real evidence .. jfk, I mean .. the test fails?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124582517>
> .
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by davetheninja** [comment] 2015-07-24 17:14
Please ignore the random things checked in, main thing to look at is the
acceptance test and the dummy app

On 25 July 2015 at 01:12, David Lawton <david@davetheninja.net> wrote:

> I seriously doubt that one will fail as its testing internals to factory
> guy.
>
> The bug is between factory guy and mockjax -> jsoanapi not understanding
> the attributes.
>
> In my tired state i could not get git patch to work....
>
> https://github.com/davetheninja/ember-data-factory-guy
>
> checked in to a fork.
>
> Please have a look-see
>
> On 25 July 2015 at 01:09, Daniel Sudol <notifications@github.com> wrote:
>
>> really .. you found real evidence .. jfk, I mean .. the test fails?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danielspaniel/ember-data-factory-guy/issues/108#issuecomment-124582517>
>> .
>>
>
>
>
> --
> "I am not able to rightly apprehend the kind of confusion of ideas that
> could provoke such a question." -- Charles Babbage
>



-- 
"I am not able to rightly apprehend the kind of confusion of ideas that
could provoke such a question." -- Charles Babbage

**Comment by danielspaniel** [comment] 2015-07-24 17:15
got it .. checking ..

**Comment by danielspaniel** [comment] 2015-07-24 18:55
That was a good point about going to acceptance test, and it did indeed fail.  I fixed that test .. but that broke a ton of other things, so this is not going to be an easy peasy .. slap in some super glue and go back to work operation .. might take all weekend. So stand by.

**Comment by davetheninja** [comment] 2015-07-24 18:56
If you need any help just ping me



—

**Comment by danielspaniel** [comment] 2015-07-27 18:23
I am 80% done with the fix for this .. was a total overhaul of fixture production .. so stand by another day or two for the fixed up new version.

**Comment by linstula** [comment] 2015-07-27 20:32
awesome, let me know if I can help out with anything :+1:

**Comment by danielspaniel** [comment] 2015-07-27 21:12
thanks for offering .. :-) preciate  it

**Comment by davetheninja** [comment] 2015-07-28 05:14
Jammin'!



—

**Comment by danielspaniel** [comment] 2015-07-30 04:14
version 1.13.3 now fixes this issue .. that was a whooper of a refactor .. let me know if it works for you too.

**Comment by davetheninja** [comment] 2015-07-30 04:14
Brilliant thanks 



—

**Comment by danielspaniel** [comment] 2015-07-30 14:46
ooops .. forgot to publish that .. which I just did, so now iversion 1.13.3 is available on npm

**Comment by danielspaniel** [comment] 2015-07-31 15:07
@davetheninja and @linstula can you confirm that this new version fixes your issues, I can close this ( or you can close if so )

**Comment by davetheninja** [comment] 2015-07-31 15:08
Will.check and get back to you tomorrow. 



—

**Comment by linstula** [comment] 2015-07-31 17:34
@danielspaniel my initial run through still shows that keys are not being dasherized for relationships or attributes. I pushed up a branch to my fork with changes that work for my use case: https://github.com/danielspaniel/ember-data-factory-guy/compare/master...linstula:dasherize-for-jsonapi. It does cause some test failures though.

ember-data: 1.13.5
ember: 1.13.3
ember-data-factory-guy: 1.13.3

Factories:
```javascript
// tests/factories/document.js
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('document', {
  default: {
    coverLetter: FactoryGuy.belongsTo('cover-letter', { async: true }),
    pages: FactoryGuy.hasMany('page', 3)
  }
});
```
```javascript
// tests/factories/cover-letter.js
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('cover-letter', {
  default: {
    body: 'Get ready to view your doc!',
    isComplete: false
  }
});
```

Result after calling `FactoryGuy.build('document')`:
![camelcase keys](https://cloud.githubusercontent.com/assets/2481432/9013182/6def6438-3788-11e5-9e41-d123c96f5919.png)

**Comment by danielspaniel** [comment] 2015-08-01 04:01
Yikes .. that is a bummer @linstula, I am going to check out your fork this weekend.

**Comment by danielspaniel** [comment] 2015-08-01 04:09
Ok .. just checked what you did in the fork, and just for funsies, can you tell me how exactly you are using factory guy ( be super specific .. I love your graphics example by the way )  to get the undasherized attrs.
 The reason I ask is because I am super curious, since there is a bit of hokus pokus going on for factory guy to dasherize things.  First the jsonapi-converter just converts to jsonapi. I purposely did not want to dasherize there .. then there is transformer to dasherize later. See the jsonapi-attributes-transformer class, and then see the jsonapi-fixture-builder .. anyway .. if you tell me what you did to get your result I can see if I can tease out a great answer for you.

**Comment by danielspaniel** [comment] 2015-08-01 18:47
Oops, @linstula  ... must have been tired, I did not see you were doing FactoryGuy.build .. duh .. sorry for my silly response.  
 Ok .. well .. I think you have a good point there .. because in build I am not transforming the json, since for FactoryGuy to make the model, it does not need to be, and I think it actually breaks things if I do transform the json attributes before pushing the json directly to the store ( as make does ) .. 
 I am checking on this now and seeing what I can do about that.

**Comment by danielspaniel** [comment] 2015-08-03 17:44
@linstula, can you check out v1.3.4 ?  I just released this version and it fixes the issues of jsonapi keys completely and once and for all ( I like the sound of that .. but of course I know it's not over )

**Comment by linstula** [comment] 2015-08-04 13:25
Awesome! I won’t be able to get to it for a few days but I’ll check out the
new version later this week.

On Monday, August 3, 2015, Daniel Sudol <notifications@github.com> wrote:
> @linstula, can you check out v1.3.4 ? I just released this version and it
fixes the issues of jsonapi keys completely and once and for all ( I like
the sound of that .. but of course I know it's not over )
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/7AC3uEN7uvMReqfskgDJPWnT6orHA-DJRMb5h-DrH7W7TgL2EtPWCHw5AYGGHnKiIryYLIJNuqkVjz0KeaOgQN0enhb-Pbfo5cI6vPndFdD6C6bvq6AWOQ9cS_nlfg2g_lfFaLfuHzj-4NErSRHaDEzzxR6yLA=s0-d-e1-ft#https://github.com/notifications/beacon/ACXdGIAeqep2XLigdqK4_nWYQWZNL_ESks5oj5_ugaJpZM4FcAC4.gif
>

**Comment by danielspaniel** [comment] 2015-08-04 13:46
Ok .. great .. and just to be safe, use factory guy v1.3.5 ( fixed build hanging issue )  


     On Tuesday, August 4, 2015 9:25 AM, linstula <notifications@github.com> wrote:
   

 Awesome! I won’t be able to get to it for a few days but I’ll check out the
new version later this week.

On Monday, August 3, 2015, Daniel Sudol <notifications@github.com> wrote:
> @linstula, can you check out v1.3.4 ? I just released this version and it
fixes the issues of jsonapi keys completely and once and for all ( I like
the sound of that .. but of course I know it's not over )
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/7AC3uEN7uvMReqfskgDJPWnT6orHA-DJRMb5h-DrH7W7TgL2EtPWCHw5AYGGHnKiIryYLIJNuqkVjz0KeaOgQN0enhb-Pbfo5cI6vPndFdD6C6bvq6AWOQ9cS_nlfg2g_lfFaLfuHzj-4NErSRHaDEzzxR6yLA=s0-d-e1-ft#https://github.com/notifications/beacon/ACXdGIAeqep2XLigdqK4_nWYQWZNL_ESks5oj5_ugaJpZM4FcAC4.gif

**Comment by linstula** [comment] 2015-08-07 13:25
Looks great @danielspaniel! Thanks for the fix! :+1:

**Comment by davetheninja** [comment] 2015-08-07 13:26
So far so good for me. Upgraded in the offixe and no issues so far. 



—

**Comment by danielspaniel** [comment] 2015-08-11 11:44
Great .. thanks for checking

**Closed by danielspaniel** 2015-08-11 11:44 UTC
