### ISSUE TITLE
TypeError: more.getModelPayload is not a function

### ISSUE THREAD

**Issue by kiesia** [danielspaniel/ember-data-factory-guy#283] opened 2017-04-08 10:27 UTC
I'm running into this error when trying to include a relationship record in the query. Do you have any idea what could be going on? I'm using Ember 2.11 and factory-guy 2.12.3. Thanks in advance!

```
TypeError: more.getModelPayload is not a function
    at _default.add (http://localhost:7357/assets/vendor.js:118933:27)
```

```
import { authenticateSession } from 'dm/tests/helpers/ember-simple-auth';
import { describe, it, beforeEach, afterEach } from 'mocha';
import { expect } from 'chai';
import startApp from '../../helpers/start-app';
import destroyApp from '../../helpers/destroy-app';
import mockCurrentUser from '../../helpers/mock-current-user';
import {
  build,
  mockQuery,
  mockSetup,
  mockTeardown
} from 'ember-data-factory-guy';

describe('Acceptance | donations/index-with-bug', function() {
  let application;

  beforeEach(function() {
    application = startApp();
    mockSetup();
  });

  afterEach(function() {
    mockTeardown();
    destroyApp(application);
  });

  context('When authenticated', function() {
    beforeEach(function() {
      authenticateSession(application);
      mockCurrentUser();
      mockQuery('message');
      mockQuery('contact');
    });

    describe('Reconciliation', function() {
      it('donation can be reconciled to an already imported xero-sourced contact', function() {
        let xeroContact = build('xero-contact');
        let contact = build('contact', { xeroContact: xeroContact }).add({ json: xeroContact });
        let donation = build('donation', { xeroContact: xeroContact, state: 'new' }).add({ json: xeroContact });

        mockQuery('donation').returns({ json: donation });
        mockQuery('contact').returns({ json: contact });

        visit('/donations');
        click('button.reconcile');

        return andThen(() => {
          expect(find('.has-imported-xero-contact').length).to.equal(1);
        });
      });
    });
  });
});
```

**Comment by danielspaniel** [comment] 2017-04-08 11:07
```javascript
 // This is suspicious .. why you adding xeroContact to a payload that already has it as a relationship?? 
let contact = build('contact', { xeroContact: xeroContact }).add({ json: xeroContact });
// here your doing it again .. your adding xeroContact as relation to donation but you already set it in the payload ?? 
let donation = build('donation', { xeroContact: xeroContact, state: 'new' }).add({ json: xeroContact });
```

I don't know your data model so I can't help you further unless I know exactly what that looks like AND exactly what the payload is supposed to be .. 
 I can Screen Hero to help out if you need ( faster then typing )

**Comment by kiesia** [comment] 2017-04-09 07:36
>  This is suspicious .. why you adding xeroContact to a payload that already has it as a relationship??

I wasn't sure if it was correct, but it errored with or without the `xeroConatact: xeroContact`. Here are my models and a normal server response. Thanks!

Donation:
```
export default Model.extend({
  source: attr('string'),
  state: attr('string'),
  transactionDate: attr('date', { defaultValue: new Date() }),
  amount: attr('number'),
  reference: attr('string'),
  description: attr('string'),

  charity: belongsTo('charity'),
  contact: belongsTo('contact'),
  xeroContact: belongsTo('xero-contact'),
  notes: hasMany('note'),
  // snip some computed values 
})
```

Contact:
```
export default Model.extend({
  state: attr('string'),
  source: attr('string'),
  firstName: attr('string'),
  lastName: attr('string'),
  email: attr('string'),
  phone: attr('string'),
  taxNumber: attr('string'),
  addressLineOne: attr('string'),
  addressLineTwo: attr('string'),
  suburb: attr('string'),
  city: attr('string'),
  postcode: attr('string'),
  country: attr('string'),
  birthdate: attr('date'),
  postLetter: attr('boolean'),
  createdAt: attr('date'),
  updatedAt: attr('date'),

  charity: belongsTo('charity'),
  donations: hasMany('donation'),
  xeroContact: belongsTo('xero-contact'),
  notes: hasMany('note'),
  // snip some computed values 
})
```

Xero Contact:
```
export default Model.extend({
  xeroId: attr('string'),
  fullName: attr('string'),
  firstName: attr('string'),
  lastName: attr('string'),
  email: attr('string'),
  phone: attr('string'),
  addressLineOne: attr('string'),
  addressLineTwo: attr('string'),
  suburb: attr('string'),
  city: attr('string'),
  postcode: attr('string'),

  contact: belongsTo('contact'),
  donation: belongsTo('donation')
});
```

Payload is kust JSONapi: 

```
{
    "data": [{
        "id": "198",
        "type": "contacts",
        "attributes": {
            "state": "live",
            "source": null,
            "first_name": "Alysa",
            "last_name": "Altenwerth the III",
            "email": "immanuel@reynolds.biz",
            "phone": "622.109.6894 x816",
            "tax_number": null,
            "address_line_one": "1000 Sickamore Ln.",
            "address_line_two": null,
            "suburb": "La La land",
            "city": "Westleyfurt",
            "postcode": "33744-5812",
            "country": "New Zealand",
            "birthdate": "1973-09-01T14:00:00.000Z",
            "post_letter": true
        },
        "relationships": {
            "donations": {
                "data": [{
                    "id": "318",
                    "type": "donations"
                }]
            },
            "xero_contact": {
                "data": null
            }
        }
    }, {
        "id": "3117",
        "type": "contacts",
        "attributes": {
            "state": "live",
            "source": "xero",
            "first_name": "Beepy",
            "last_name": "Beeper",
            "email": null,
            "phone": " ",
            "tax_number": null,
            "address_line_one": null,
            "address_line_two": null,
            "suburb": null,
            "city": null,
            "postcode": null,
            "country": null,
            "birthdate": null,
            "post_letter": false
        },
        "relationships": {
            "donations": {
                "data": []
            },
            "xero_contact": {
                "data": {
                    "id": "21",
                    "type": "xero_contacts"
                }
            }
        }
    }],
    "included": [{
        "id": "21",
        "type": "xero_contacts",
        "attributes": {
            "xero_id": "29de5495-6983-40ad-8f65-548ac3756530",
            "full_name": "Beepy Beeper",
            "first_name": null,
            "last_name": null,
            "email": null,
            "phone": " ",
            "address_line_one": null,
            "address_line_two": null,
            "city": null,
            "postcode": null
        }
    }]
}
```

**Comment by danielspaniel** [comment] 2017-04-09 08:55
Ok ... great .. then in your case, this is all you need to do 

```javascript
let xeroContact = build('xero-contact');
let contact = build('contact', { xeroContact });
let donation = build('donation', { xeroContact, state: 'new' });
// assuming you want to same xeroContact for both, but you can make a different one or use null if you want. 

mockFindRecord('contact').returns({ json: contact });
mockFindRecord('donation').returns({ json: donation });
```
 What happens when you 'build' a payload like this is that your contact belongsTo xeroContact, 
 so the jsonapi payload will automatically "include" the relation ship just like you want it to .. 
 nothing you have to do at all. Sorry to say, it is that simple.
 
 I think the problem is that the doc's are not clear enough to make this obvious enough. I do show how to build a payload but maybe not enough examples to show exactly what the payload will look like for this or that case. The tests have plenty of examples, so you can scan those for now? 

 If you feel like improving the documentation .. please feel free to take out your frustrations on a PR that does a better job of explaining this ??

**Comment by danielspaniel** [comment] 2017-04-16 13:21
@kiesia .. can you let me know if you are still confused, need more help, or are all set. Should I close this issue?

**Comment by kiesia** [comment] 2017-04-17 13:00
@danielspaniel thanks for your reply! I've been on the road the last week, but I'll be able to fix up my tests tomorrow. I'd be happy to update the docs too.

**Comment by kiesia** [comment] 2017-04-18 08:06
@danielspaniel that's working perfectly, thanks again! I've just moved town, I'll have to get settled first and then will look at those docs.

**Comment by danielspaniel** [comment] 2017-05-11 11:01
Closing this since the issue seems fixed. 
Hope you get to fixing the documentation to make it better @kiesia .. 😄

**Closed by danielspaniel** 2017-05-11 11:01 UTC
