### ISSUE TITLE
Cannot read property 'call' of undefined with empty factory...

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielspaniel/ember-data-factory-guy#178] opened 2016-03-03 20:54 UTC
I've commented out nearly everything to try to narrow down the cause of this error.

```

test('_eligibleForDiscount | true when membershipOption added', function(assert) {
  // let membershipOption = make('membership-option');
  let organization = make('organization', {
    // membershipOptions: [membershipOption]
  });
  // let order = make('order', {
  //   host: organization
  // });
  //
  // order.addLineItem(membershipOption);
  //
  // let result = order._eligibleForDiscount();
  //
  // assert.equal(result, true);
});
```

and then my factory:

```
// tests/factories/organization.js

import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('organization', {
  default: {
    type: 'organization'
  }
});

```

not sure what's up with this, cause the factory is pretty much the same as my others.. just with a different word placed in for define and type.

**Comment by danielspaniel** [comment] 2016-03-03 21:06
is organization polymorhpic?  it does not need the type if it's not ?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:07
yeah, it's a type of 'host'

how do I do that?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:12
```
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('organization', {
  default: {
    type: 'host'
  }
});
```

gives the same error :-\

**Comment by danielspaniel** [comment] 2016-03-03 21:16
organization is fine then .. there is something here that I am not seeing .. ( obviously ) .. you on screen hero?  can I check it out and see what's up

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:20
looks like I needed to then define a `host` factory -- now my test isn't throwing an error (other than teh assert failing)

I guess it wasn't clear that:
- Factories for parents of polymorphic children must be defined.
- extends references a factory

I now have:

```
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('organization', {
  extends: 'host'
});
```

and 
```
import FactoryGuy from 'ember-data-factory-guy';

FactoryGuy.define('host', {});
```

**Comment by danielspaniel** [comment] 2016-03-03 21:22
ooo .. ok .. I will make a test for that because I don't have a ton of polymorphic factories but I never had it set up like you did .. will try and reproduce it. 
 also .. keep the type: organization for the organization type .. ( I am 80% sure that's important ) . but if you find it's not .. then let me know ..

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:30
actually, I'm still getting the error now -- no idea how it worked the one time.

**Comment by danielspaniel** [comment] 2016-03-03 21:31
can you make a host?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:32
`make('host')` has the same error

**Comment by danielspaniel** [comment] 2016-03-03 21:34
what does model look like?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:38
models:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/models/host.js
^ 
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/models/community.js
^ 
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/models/organization.js

factories:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/tests/factories/host.js
^
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/tests/factories/organization.js

**Comment by danielspaniel** [comment] 2016-03-03 21:42
can you stop doing this ?
```js
  type: function () {
    return this.constructor.modelName;
  }.property(),
```

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:52
in which factory / model?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:52
is type a keyword?

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:53
anywho, I don't think I was using it. I do get tho constructor.modelName quite a bit in other places though

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:54
remove it didn't help the error though. :-\

**Comment by danielspaniel** [comment] 2016-03-03 21:54
its in host. 
 it's not a keyword for ember .. but is not your backend db setting that type field .. usually it does. 
 ok .. got it

**Comment by danielspaniel** [comment] 2016-03-03 21:55
what is exact error and exact stack trace ? need more info

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:58
I was going to take a screen shot, but the test runner is in a VM, so I loaded the test URL in my host-OS browser, and the error went away.... so weird.

VM: 
![image](https://cloud.githubusercontent.com/assets/199018/13510931/0d98c8a8-e161-11e5-828d-d5a4dffa1ced.png)

Host-OS:
![image](https://cloud.githubusercontent.com/assets/199018/13510942/16847818-e161-11e5-95cc-43eedc61d853.png)


wat

**Comment by NullVoxPopuli** [comment] 2016-03-03 21:59
ok, here we go, I'm now doing `make('organization')`

![image](https://cloud.githubusercontent.com/assets/199018/13510972/40a38fd0-e161-11e5-9fbc-4f60d4e83a74.png)

**Comment by danielspaniel** [comment] 2016-03-03 21:59
ahh .. that is great .. thanks .. might take me a bit to work out the bug .. but I will get it with this info

**Comment by NullVoxPopuli** [comment] 2016-03-03 22:01
ok cool. If it'll help, feel free to clone my repo -- I've started mocking the api, so you don't need to setup a backend or anything.

**Comment by NullVoxPopuli** [comment] 2016-03-03 22:02
Also, if there is anything you need me to do, I'm more than happy to help.

**Comment by danielspaniel** [comment] 2016-03-03 22:02
also you set up that repo so I can clone that ( just did ) .. and will test on there .. thanks for offer

**Comment by NullVoxPopuli** [comment] 2016-03-03 22:03
my repo: https://github.com/NullVoxPopuli/aeonvera-ui

**Comment by NullVoxPopuli** [comment] 2016-03-03 22:06
the tricky test is in tests/unit/models/order-test.js

**Comment by danielspaniel** [comment] 2016-03-03 22:18
perfect .. thanks :)

**Comment by danielspaniel** [comment] 2016-03-03 23:25
ugh .. you forgot to read the documentation

```js 
import {  make,  manualSetup } from 'ember-data-factory-guy';

moduleForModel('order', 'Unit | Model | order', {
  // Specify the other units that are required for this test.
  needs: ['model:organization'],
  beforeEach() { manualSetup(this.container) }
});
```

I even give a sample model test  in the testing models, components section.. 

[https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/unit/models/profile-test.js]

The only reason I don't throw breadcumbs at you is because my error reporting was terrible .. so I throw them at myself instead.

**Comment by NullVoxPopuli** [comment] 2016-03-03 23:34
oh shoot. Well, now I feel bad. 

Sorry man.

I did go back and look at the documentation just now. Sure enough, it's right here: https://github.com/danielspaniel/ember-data-factory-guy#testing-models-controllers-components

:-(

thanks for looking in to that. I hope this didn't waste too much of your time

**Comment by danielspaniel** [comment] 2016-03-03 23:37
no .. I feel bad that the error was so stupid .. my fault .. I fixed your bower.json anyway .. took out loader and ember-resolver ( was killing the bower install ) those are in package.json  and not needed in bower

**Comment by NullVoxPopuli** [comment] 2016-03-03 23:37
at least now, if someone else google's this error, they'll come to the solution?

**Comment by danielspaniel** [comment] 2016-03-03 23:38
usually that would be the case, but I am fixing that error message now .. since it will happen again I am sure. Not so easy to fix .. ( oddly ) .. but I will do that ..

**Comment by NullVoxPopuli** [comment] 2016-03-03 23:38
oh wow, I didn't even know those were cause that issue, thanks a ton!

I've been finding that there could always be more error handling in ember, and related tools.

**Comment by danielspaniel** [comment] 2016-03-03 23:40
sure thing .. I could spend all day on that repo fixing things .. because I am anal retentive .. but hey .. it's not my job .. gotta keep doing this other thing. anyway ... was actually nice to get this one fixed in the end.

**Comment by NullVoxPopuli** [comment] 2016-03-03 23:40
woo! you rock, dude!!!! :+1:

**Comment by danielspaniel** [comment] 2016-03-03 23:41
thanks mate .. I will close this when I fix that error message

**Comment by danielspaniel** [comment] 2016-03-04 02:06
the message is now pretty spiffy in v2.3.3 .. :)

**Closed by danielspaniel** 2016-03-04 02:06 UTC

**Comment by NullVoxPopuli** [comment] 2016-03-04 04:30
just upgraded to 2.3.3

it can't find the models?

![image](https://cloud.githubusercontent.com/assets/199018/13518071/dc212f9a-e197-11e5-9b3c-aaed3d26154a.png)

**Comment by danielspaniel** [comment] 2016-03-04 09:29
Looks like an error with factory guy .. but what the actual problem is ( is ) that you forgot to put needs: 'model:lesson'  in your list of models you "need" at the top of your unit test.   Might have to add some error messages there too to help out.

**Comment by NullVoxPopuli** [comment] 2016-03-04 11:05
man, I needed a ton of includes. haha. thanks!!!

**Comment by danielspaniel** [comment] 2016-03-04 11:14
sometimes you can get away with doing integration: true, rather than unit: true even in moduleForModel, to avoid that needs infinity.
