### ISSUE TITLE
FactoryGuy.hasMany fails with error `'undefined' is not an object (evaluating 'traits[trait]')`

### ISSUE THREAD

**Issue by mattmcmanus** [danielspaniel/ember-data-factory-guy#80] opened 2015-05-05 18:22 UTC
I'm running into this issue with trying to test a model that has an association on it. I found a temporary solution but I've yet to understand the root cause or how to test it (I'm new to ember). Anyway, here is what I hope is all of the relevant info

### The models
```js
// app/group/model.js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),

  users: DS.hasMany('user')
});

// app/user/model.js
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  email: DS.attr('string'),
  role: DS.attr('string'),
  last_signed_in_at: DS.attr('datetime')
});

```
### The factories
```js
// tests/factories/group.js
import FactoryGuy from 'ember-data-factory-guy';
import faker from 'faker';

FactoryGuy.define('group', {
  default: {
    name: faker.company.companyName()
  },

  traits: {
    with_users: { users: FactoryGuy.hasMany('user', 4) }
  }
});

// tests/factories/user.js
import FactoryGuy from 'ember-data-factory-guy';
import faker from 'faker';

FactoryGuy.define('user', {
  default: {
    name: faker.name.findName(),
    email: faker.internet.email(),
    role: 'member',
    last_signed_in_at: Date.now()
  },

  admin_user: {
    role: 'admin'
  }
});

```
### The test
```js
// tests/unit/group/model-test.js
import Ember from 'ember';
import startApp from 'client/tests/helpers/start-app';
import { module, test } from 'qunit';

import { make } from 'ember-data-factory-guy';

var application;

module('Group model', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('it exists', function(assert) {
  let group = make('group');
  assert.ok(!!group);
  assert.ok(group.get('name'));
});

test('it can have user', function(assert){
  let group = make('group','with_users');

  assert.equal(group.get('users.length'), 4, '4 of them');
});

```
### The error
```
not ok 3 PhantomJS 1.9 - Group model: it can have user
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2809
                at http://localhost:7357/assets/client.js:3188
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:5578: 'undefined' is not an object (evaluating 'traits[trait]')
        Log: >
    ...
```
What causing the error is the association line in my group factory trait for users. If I remove the `hasMany`, I receive no error. 

```js
traits: {
 with_users: { users: FactoryGuy.hasMany('user', 4) }
}
```

### What fixes it
So what's bombing out there is `model-definition.js`
```js
  this.build = function (name, opts, traitArgs) {
    var traitsObj = {};
    traitArgs.forEach(function (trait) {
      $.extend(traitsObj, traits[trait]);
    });
...
```
For some reason, the `extractArguments` method is actually setting traits = `undefined` which is then causing that `traitArgs` argument in `build()` to equal an array with a single value of undefined (`[undefined]`)

Now, I have no idea if that is desired or not, i've only dug around trying to get this to work for an hour or two. What got things to work for me was putting in a guard clause. 

```js
traitArgs.forEach(function (trait) {
  if (!trait) return;
  $.extend(traitsObj, traits[trait]);
});
```

If that really does fix it, great. Otherwise, I hope all of this rambling is enough to point you in the right direction of fixing the bug or telling me what obvious thing I missed. Thanks!

### Versions
```
DEBUG: -------------------------------
ember.debug.js:5197DEBUG: Ember                     : 1.11.1
ember.debug.js:5197DEBUG: Ember Data                : 1.0.0-beta.16.1
ember.debug.js:5197DEBUG: jQuery                    : 1.11.3
ember.debug.js:5197DEBUG: Ember Simple Auth         : 0.8.0-beta.2
ember.debug.js:5197 DEBUG: Ember Simple Auth Devise  : 0.8.0-beta.2
ember.debug.js:5197 DEBUG: Ember Simple Auth Testing : 0.8.0-beta.2
ember.debug.js:5197 DEBUG: -------------------------------
    "ember-data-factory-guy": "1.0.5",
```

**Comment by danielspaniel** [comment] 2015-05-05 18:53
@mattmcmanus, I pushed a fix for that case and it is on v1.0.7 .. so can you upgrade to that version of factory guy and let me know if that fixes it for you. Thanks for the rambling report .. it helps to see the whole story, even though in this case I could not quite recreate it.

**Comment by mattmcmanus** [comment] 2015-05-05 19:47
Works for me. 

Thanks Daniel. I knew this one would be hard to reproduce, which usually means there is something that I was missing but I working solo on this. I figured the best thing was to get another set of eyes on it. Thanks for the quick turn around!

**Closed** 2015-05-05 19:47 UTC

**Comment by danielspaniel** [comment] 2015-05-05 19:51
No problem @mattmcmanus , and there are always these little edge cases that just poke their noses in every once in a while, so even though I could not reproduce, ( and your tests looked fine to me btw .. pretty straighforward, no funny business ) , so it was good to address it and so the next person does not find it.
