### ISSUE TITLE
`Cannot read property '_super' of undefined` with Ember 2.10.0

### ISSUE THREAD

**Issue by GavinJoyce** [danielspaniel/ember-data-factory-guy#260] opened 2016-11-29 12:46 UTC
We're seeing a large number of our tests fail in Ember 2.10.0 which pass in Ember 2.9.0. 

Here is a dummy app which demonstrates the issue:

https://github.com/GavinJoyce/glammer/pull/10

**Ember 2.9.0:**

<img width="847" alt="screen shot 2016-11-29 at 12 41 18" src="https://cloud.githubusercontent.com/assets/2526/20710271/6c575382-b631-11e6-9e66-7de6bcea0427.png">

**Ember 2.10.0:**

<img width="909" alt="screen shot 2016-11-29 at 12 41 43" src="https://cloud.githubusercontent.com/assets/2526/20710275/70c0649a-b631-11e6-9778-f4414b8dd8aa.png">

**Comment by GavinJoyce** [comment] 2016-11-29 12:55
Here are the stack traces:

**Ember 2.9.0:**

<img width="1273" alt="screen shot 2016-11-29 at 12 54 45" src="https://cloud.githubusercontent.com/assets/2526/20710584/0bcff4ae-b633-11e6-964e-f9b57a3d8fb9.png">

**Ember 2.10.0:**

<img width="1265" alt="screen shot 2016-11-29 at 12 52 48" src="https://cloud.githubusercontent.com/assets/2526/20710588/1019bfea-b633-11e6-96bd-3e7d10ead609.png">

**Comment by GavinJoyce** [comment] 2016-11-29 13:25
The test failure happens with both `Ember Data 2.9.0` and `Ember Data 2.10.0`:

<img width="728" alt="screen shot 2016-11-29 at 13 23 59" src="https://cloud.githubusercontent.com/assets/2526/20711394/5805f50e-b637-11e6-935b-4f410dd6a83b.png">
<img width="851" alt="screen shot 2016-11-29 at 13 24 58" src="https://cloud.githubusercontent.com/assets/2526/20711395/5806842e-b637-11e6-8de1-b48c56784abc.png">

**Comment by danielspaniel** [comment] 2016-11-29 13:29
Ok .. let me bump up to ember 2.10.0 and see what I can find

**Comment by GavinJoyce** [comment] 2016-11-29 13:30
Thanks @danielspaniel. I'll continue to dig into it from my side too

**Comment by GavinJoyce** [comment] 2016-11-29 13:37
Some [chatter on `#dev-ember`](https://embercommunity.slack.com/archives/dev-ember/p1480424238005685):

<img width="643" alt="screen shot 2016-11-29 at 13 37 10" src="https://cloud.githubusercontent.com/assets/2526/20711700/f3bf751e-b638-11e6-8236-b1d2f15bf38e.png">

**Comment by danielspaniel** [comment] 2016-11-29 14:03
Very odd.. I get no issues on my acceptance tests, only component tests.  Oddly, on another repo ember 2.10.0 my component tests are fine ( using ember-mocha ) . This is puzzler.  Must be some version of qunit ( or something else )  as well ( that makes difference )  because we are seeing different results for same ember/data versions.

**Comment by patocallaghan** [comment] 2016-11-29 14:03
@danielspaniel so after digging in with @GavinJoyce it appears that it could be a combination of using the `EmbeddedRecordsMixin` with the `RESTAdapter` and the `JSONSerializer`.

The `comments` property on the `post` model is a `hasMany` of the `comment` model. The `comment` model has a custom serializer  which uses the `EmbeddedRecordsMixin`. If you remove that mixin it works as expected.

![image](https://cloud.githubusercontent.com/assets/685034/20712385/b7e95746-b63b-11e6-8b2e-39d98b46e9c9.png)

I've tried to reproduce it in the Factory Guy tests but having trouble currently, possibly due to the way the shared-adapter-tests are set up.

**Comment by danielspaniel** [comment] 2016-11-29 14:15
Ok .. that makes sense .. because that was an ember-data failure .. is that considered an illegal procedure? ( EmbeddedRecordsMixin with JSON serializer ) ..  I think so .. but wonder how you can work around that. you could switch to RestAdapter/RestSerializer and pass the root in the json payload ... that would be the best for long term sanity. 
 
I made special tests just for you with that combination or RESTAdapter/JSONSerializer and you're right, there is special hokus pokus in the testing which might be masking this (ember-data bug ). 

Let me know what your thoughts are on what direction your going to take.  I vote for long term sanity. But I don't know exactly whey you are doing that combination of Adapter/Serializer so I can't say for sure that some quick fix might be in order.

**Comment by patocallaghan** [comment] 2016-11-29 14:25
Looking at the Ember Data docs it appears that combination is supported https://guides.emberjs.com/v2.9.0/models/customizing-serializers/#toc_embeddedrecordmixin

The example code given is:

```js
import DS from 'ember-data';

export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    authors: { embedded: 'always' }
  }
});
```

The reason we use this combination is to continue to use an endpoint format which we were using with Ember Model.

**Comment by danielspaniel** [comment] 2016-11-29 14:27
Ok .. great .. glad to be wrong about that ..  

 let me know if you think there is something I can do to help.

**Comment by GavinJoyce** [comment] 2016-11-29 14:38
@danielspaniel this seems to happen to `DS.RESTSerializer` too:

```js
export default DS.RESTSerializer.extend({
  keyForRelationship() {
    console.log('keyForRelationship');
    return this._super(...arguments);
  }
});
```

**Comment by danielspaniel** [comment] 2016-11-29 14:41
Ooo .. interesting .. that is actually good news because it's not whacky edge case. Just plain broken.

**Comment by GavinJoyce** [comment] 2016-11-29 14:54
Changing [this](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/converter/fixture-converter.js#L137) from:

`return attrName || keyFn(attribute, kind);`

to

`return attrName || keyFn.call(this, attribute, kind);`

seems to fix it.

I'm going to test if something changed between ember versions next

**Comment by danielspaniel** [comment] 2016-11-29 15:00
Oh .. great .. glad to be wrong about that too .. that it was not ember-data bug .. and it's something in factory guy that is triggering that

**Comment by GavinJoyce** [comment] 2016-11-29 15:22
It looks like it may be a framework bug: https://github.com/GavinJoyce/glammer/pull/11

**Comment by danielspaniel** [comment] 2016-11-29 15:35
that is true ( about the this scope being lost ) , the code I have should have barfed long ago.  
There must have been something ember was doing to cover it or 
you were doing that actually used the serializer function and then it barfed.  ?? 
  Just a thought.

**Comment by GavinJoyce** [comment] 2016-11-29 15:45
> you were doing something recently that actually used the serializer function and then it barfed

Something changes between 2.9 and 2.10. rwjblue and mixonic are trying to discover what caused the change. Although the new behaviour is correct, I don't believe that it was a conscious decision.

**Comment by GavinJoyce** [comment] 2016-11-29 15:45
Here's a twiddle: https://ember-twiddle.com/ac831005599534deac030080835456e0?openFiles=controllers.application.js%2C

**Comment by GavinJoyce** [comment] 2016-11-29 15:53
<img width="725" alt="screen shot 2016-11-29 at 15 51 27" src="https://cloud.githubusercontent.com/assets/2526/20716941/c9513d36-b64b-11e6-99cb-ad2a16ed6728.png">
<img width="630" alt="screen shot 2016-11-29 at 15 51 35" src="https://cloud.githubusercontent.com/assets/2526/20716945/cc571f1e-b64b-11e6-9840-fdf6352d96f5.png">
<img width="950" alt="screen shot 2016-11-29 at 15 53 19" src="https://cloud.githubusercontent.com/assets/2526/20717016/faf95b3e-b64b-11e6-8b8e-42d2a4e97e20.png">

**Comment by danielspaniel** [comment] 2016-11-29 15:55
wow .. talk about obscure whacky issue.  Glad you / they uncovered the cause. Nice twiddle by the way .. pretty slick.

**Comment by danielspaniel** [comment] 2016-11-29 15:57
I think the test would be to just override serializer method to  force the barfing  .. will try it out later today

**Comment by GavinJoyce** [comment] 2016-11-29 15:59
@danielspaniel thanks, a test would be great. I'm not familiar with `ember-data-factory-guy` so that would be a big help

**Comment by danielspaniel** [comment] 2016-11-29 16:02
working on it now

**Comment by danielspaniel** [comment] 2016-11-29 18:04
fixed in https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.9.4

**Closed by danielspaniel** 2016-11-29 18:04 UTC

**Comment by GavinJoyce** [comment] 2016-11-29 18:23
It looks like some `console.log`s slipped in: https://github.com/danielspaniel/ember-data-factory-guy/commit/c6d4ed0cbbd6889f10fb60739f4b938b3393c20f

**Comment by patocallaghan** [comment] 2016-11-29 18:28
I've a PR to remove them here https://github.com/danielspaniel/ember-data-factory-guy/pull/262
